database.url=mongodb+srv://<db_username>:<db_password>@cluster0.mxvgqnx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
database.name=URLShortenerDB
database.collection=URLs
application.version=1.0.0
